// Code generated by xgen. DO NOT EDIT.

package mets

import (
	"encoding/xml"
)

// Href ...
type Href string

// Role ...
type Role string

// Arcrole ...
type Arcrole string

// Title ...
type Title string

// Show ...
type Show string

// Actuate ...
type Actuate string

// Label ...
type Label string

// From ...
type From string

// To ...
type To string

// SimpleLink ...
type SimpleLink struct {
	//	XMLName          xml.Name `xml:"simpleLink"`
	TypeAttr         string `xml:"xlink:type,attr,omitempty"`
	XlinkHrefAttr    string `xml:"xlink:href,attr,omitempty"`
	XlinkRoleAttr    string `xml:"xlink:role,attr,omitempty"`
	XlinkArcroleAttr string `xml:"xlink:arcrole,attr,omitempty"`
	XlinkTitleAttr   string `xml:"xlink:title,attr,omitempty"`
	XlinkShowAttr    string `xml:"xlink:show,attr,omitempty"`
	XlinkActuateAttr string `xml:"xlink:actuate,attr,omitempty"`
}

// ExtendedLink ...
type ExtendedLink struct {
	XMLName        xml.Name `xml:"extendedLink"`
	TypeAttr       string   `xml:"type,attr,omitempty"`
	XlinkRoleAttr  string   `xml:"xlink:role,attr,omitempty"`
	XlinkTitleAttr string   `xml:"xlink:title,attr,omitempty"`
}

// LocatorLink ...
type LocatorLink struct {
	XMLName        xml.Name `xml:"locatorLink"`
	TypeAttr       string   `xml:"type,attr,omitempty"`
	XlinkHrefAttr  string   `xml:"xlink:href,attr"`
	XlinkRoleAttr  string   `xml:"xlink:role,attr,omitempty"`
	XlinkTitleAttr string   `xml:"xlink:title,attr,omitempty"`
	XlinkLabelAttr string   `xml:"xlink:label,attr,omitempty"`
}

// ArcLink ...
type ArcLink struct {
	XMLName          xml.Name `xml:"arcLink"`
	TypeAttr         string   `xml:"type,attr,omitempty"`
	XlinkArcroleAttr string   `xml:"xlink:arcrole,attr,omitempty"`
	XlinkTitleAttr   string   `xml:"xlink:title,attr,omitempty"`
	XlinkShowAttr    string   `xml:"xlink:show,attr,omitempty"`
	XlinkActuateAttr string   `xml:"xlink:actuate,attr,omitempty"`
	XlinkFromAttr    string   `xml:"xlink:from,attr,omitempty"`
	XlinkToAttr      string   `xml:"xlink:to,attr,omitempty"`
}

// ResourceLink ...
type ResourceLink struct {
	XMLName        xml.Name `xml:"resourceLink"`
	TypeAttr       string   `xml:"type,attr,omitempty"`
	XlinkRoleAttr  string   `xml:"xlink:role,attr,omitempty"`
	XlinkTitleAttr string   `xml:"xlink:title,attr,omitempty"`
	XlinkLabelAttr string   `xml:"xlink:label,attr,omitempty"`
}

// TitleLink ...
type TitleLink struct {
	XMLName  xml.Name `xml:"titleLink"`
	TypeAttr string   `xml:"type,attr,omitempty"`
}

// EmptyLink ...
type EmptyLink struct {
	XMLName  xml.Name `xml:"emptyLink"`
	TypeAttr string   `xml:"type,attr,omitempty"`
}
