defaultarea = "content"
[log]
# "trace"
# "debug"
# "info"
# "warn"
# "error"
# "fatal"
# "panic"
level = "INFO"

# global config for all operations on S3 storages
[s3]
# --s3-endpoint
#Endpoint="%%GOCFL_S3_ENDPOINT%%"
# --s3-access-key-id
#AccessKeyID="%%GOCFL_S3_ACCESS_KEY_ID%%"
# --s3-secret-access-key
#AccessKey="%%GOCFL_S3_ACCESS_KEY%%"
# --s3-region
#Region="%%GOCFL_S3_REGION%%"

[aes]
enable=false
keepassfile="c:/temp/test.kdbx"
keepassentry="keepass2://test.kdbx/Root/gocfl/test"
keepasskey="%%GOCFL_KEEPASS_KEY%%"

[test]
fixturepath = "../fixtures/1.1/bad-objects"

[init]
# --ocfl-version
ocflversion="1.1"
# --default-storageroot-extensions
#StorageRootExtensions="../data/defaultextensions/storageroot"
# --digest
digest="sha512"

[add]
# --message
message="initial commit"
# --digest
digest="sha512"
# --fixity
fixity=["sha256", "sha1", "md5"]
# --default-object-extensions
#ObjectExtensions="../data/fullextensions/object"
deduplicate = false
nocompress = true

[add.user]
# --user-name
name="unknown user"
# --user-address
address="https://github.com/ocfl-archive/gocfl"

[update]
# --message
message="update"
# --digest
digest="sha512"
deduplicate = true
nocompress = true
echo = true

[update.user]
# --user-name
name="unknown user"
# --user-address
address="https://github.com/ocfl-archive/gocfl"

[display]
addr = "localhost:80"
addrext = "https://localhost:80/"

[extract]
manifest = false
version = "latest"

[extractmeta]
version = "latest"
format = "json"

[stat]
info = ["ExtensionConfigs",
    "Objects",
    "ObjectVersionState",
    "ObjectManifest",
    "ObjectFolders",
    "Extension",
    "ObjectVersions",
    "ObjectExtension",
    "ObjectExtensionConfigs"]

[initconfig]
configfolder="~/gocfl"
tomlfile="gocfl.toml"
extensionfolder="extensions"
scriptfolder="scripts"
fullconfig=false
extensions=true
scripts=true

#
# Extension parameter
#
[extension]
[extension.NNNN-metafile]
source=""

[extension.NNNN-mets]
# --ext-NNNN-mets-descriptive-metadata
descriptive-metadata="other:metadata:info.json"
#
# Indexer
#
[indexer]
enabled=true
optimize=true

[indexer.checksum]
enabled=true
digest=["sha512"]

#
# Thumbnail
#
[thumbnail]
enable=true
background="none"

#
# Migration
#
[migration]
# --with-migration
enable=false
